### ISSUE TITLE
Net::ZMQ update...

### ISSUE THREAD

**Issue by Altai-man** [bduggan/p6-jupyter-kernel#2]
...with API breakage. As https://github.com/arnsholt/Net-ZMQ/pull/17 is merged, things were broken.

#### Kernel.pm6

`Net::ZMQ::` prefix is no longer valid, use `Net::ZMQ4::` for all modules import.

#### Service.pm6

`zmq_device` is deprecated for years and `zmq_proxy` should be used instead. It works basically the same, the main difference is that you use different socket types to select flow(hence `ZMQ_FORWARDER` constant is removed too). See http://api.zeromq.org/4-2:zmq-proxy for more information. `zmq_proxy` resides in `Net::ZMQ4::Proxy` module.
https://github.com/bduggan/p6-jupyter-kernel/blob/master/lib/Jupyter/Kernel/Service.pm6#L13-L14 - this by hands definition can be removed(along with NativeCall import).

Construction of `Net::ZMQ4::Message` on client-side is discouraged and, in fact, no longer works. New API methods `send` and `sendmore` can receive `Str` or `Blob` of data, so you can rework `send` method to leave message packing on library-side and just pass Blobs|Strings of data.

#### Library info

The updated bindings are stable for zeromq of version `4.1`. It is compatible with `4.2` too, butt in my experience it is instable and crushes are almost guaranteed. It is _incompatible_ and not guaranteed at all to work with older versions(but if one wants to implement the layer of compatibility - I am fully open for pull requests).

Any questions regarding a port process can be asked here and I will explain things the best I can.

Thanks for your attention and I am truly sorry for the inconvenience of api breakage.

**Comment by bduggan** [comment]
Great, thanks for all of the details  I've made the changes, and things seem to be working fine.
