### ISSUE TITLE
Where's last result and indexed result?

### ISSUE THREAD

**Issue by clouds56** [bduggan/p6-jupyter-kernel#21]
in python kernel we can refer to them via `_` for last result and `_3` for `Out[3]`.

**Comment by bduggan** [comment]
Not yet implemented, but good idea.  I don't see any reason not to use the same variable names in this kernel.  Of course it would conflict with any usage of a variable named `_` in the user's code, but presumably the same issue exists in python, and I don't think `_` is used for anything special in Perl 6.  ( `$_` is used of course but `_` without a `sigil` isn't, as far as I know).  We also need to support allowing `Out[3]` to refer to `Out[3]`.
