### ISSUE TITLE
Kernel dies on finding semantic error

### ISSUE THREAD

**Issue by sumandoc** [bduggan/p6-jupyter-kernel#29]
While trying to divide 4 by 0, the kernel simply dies rather than throwing error message.

In Perl 6 REPL, I get informative message as:

`Attempt to divide 4 by zero using div`

but in notebook, the kernel is dead !!

Is it expected behavior?

**Comment by bduggan** [comment]
Thanks, fixed.

Failures (lazy exceptions) weren't being caught -- I've improved this, so it should be okay now.

Brian
