### ISSUE TITLE
Cell magic implementation

### ISSUE THREAD

**Issue by sumandoc** [bduggan/p6-jupyter-kernel#30]
I found a couple of cell magics here for Python notebook:

http://ipython.readthedocs.io/en/stable/interactive/magics.html

I tried these magics in `Perl 6` notebook to see if they work.

I tried to execute the following magic so that I don't have to resort to terminal to execute code:

```
%%bash
pwd
```

But it didn't show the expected behavior.

Have these magics been implemented in the kernel?

**Comment by bduggan** [comment]
I've implemented a few magics -- see <https://github.com/bduggan/p6-jupyter-kernel#features>.

A lot of the ipython magics are already pretty easy in Perl 6 without any magic, but let me know if there are some specific ones you think should be implemented.

I went ahead and added one for bash in #32.
