### ISSUE TITLE
"Lexical with name '$a' does not exist in this frame"

### ISSUE THREAD

**Issue by raiph** [bduggan/p6-jupyter-kernel#43]
See https://stackoverflow.com/questions/50221466/assignment-to-nested-lists-in-perl-6/50222378?noredirect=1#comment87463338_50222378

**Comment by bduggan** [comment]
The Jupyter kernel uses the internal `REPL` class -- so the behavior of it will be the same as the built-in REPL.  As a workaround (for either one), you could put the declarations and assignment on the same line (or in the same cell), e.g.
```
In [1]: my ($a,$b,$c); :(($a,$b), $c) := ((1,2), 3);
Out[1]: ($ ($a, $b), $c)

In [2]: $a, $b, $c
Out[2]: (1 2 3)
```
