### ISSUE TITLE
Ability to include and adjust image in Perl 6 notebook

### ISSUE THREAD

**Issue by sumandoc** [bduggan/p6-jupyter-kernel#45]
Currently image can be easily embedded in the notebook in **markdown** cell with
`![title](img/picture.png)`. The demerit of this approach is inability to adjust the size of image.

In python notebook, image can be embedded in **code** cell with code:

```
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "http://my_site.com/my_picture.jpg", width=100, height=100)
```

Can it be done in **Perl 6** notebook similarly?

**Comment by bduggan** [comment]
Hi sumandoc --

Yes, is the Python generating HTML with an image tag?   You can emit HTML from the Perl 6 kernel, like this:

```
#% html

'<img src="https://perl6.org/camelia-logo.png" width=100 height=100>'
```
