### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by anopperl** [bduggan/p6-jupyter-kernel#5]
i want to install  "p6-jupyter-kernel" 
so i typed
"zef install --deps-only" in terminal then it give me error 

Usage:
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--force|--force-fetch] fetch '[<identities> ...]' -- Download specific distributions
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--force|--force-test] test '[<paths> ...]' -- Run tests
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--force|--force-build] build '[<paths> ...]' -- Run Build.pm
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--depends] [--test-depends] [--build-depends] [--test] [--fetch] [--build] [--force] [--force-resolve] [--force-fetch] [--force-extract] [--force-build] [--force-test] [--force-install] [--dry] [--update] [--upgrade] [--deps-only] [--serial] [--exclude=<Any>] [--to|--install-to=<Any>] install '[<wants> ...]' -- Install
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--from|--uninstall-from=<Any>] uninstall '[<identities> ...]' -- Uninstall
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--wrap=<Int>] search '[<terms> ...]' -- Get a list of possible distribution candidates for the given terms
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--max=<Int>] [-i|--installed] list '[<at> ...]' -- A list of available modules from enabled repositories
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--to|--install-to=<Any>] upgrade '[<identities> ...]' -- Upgrade installed distributions (BETA)
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--depends] [--test-depends] [--build-depends] rdepends <identity> -- View reverse dependencies of a distribution
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--sha1] locate <identity> -- Lookup locally installed distributions by short-name, name-path, or sha1 id
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--wrap=<Int>] info <identity> -- Detailed distribution information
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--open] browse <identity> <url-type> -- Browse a distribution's available support urls (homepage, bugtracker, source)
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef look <identity> -- Download a single module and change into its directory
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--depends] [--test-depends] [--build-depends] [--test] [--fetch] [--build] [--force] [--force-resolve] [--force-fetch] [--force-extract] [--force-build] [--force-test] [--force-install] [--update] [--upgrade] [--deps-only] [--exclude=<Any>] [--to|--install-to=<Any>] smoke -- Smoke test
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef update '[<names> ...]' -- Update package indexes
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [--confirm] nuke '[<names> ...]' -- Nuke module installations (site, home) and repositories from config (RootDir, StoreDir, TempDir)
  /home/anopperl6/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef [-h|--help]

**Comment by MattOates** [comment]
You missed off the `.` on the end which stands for the current working directory. zef expects you to say what to install, if its not a module name it assumes the location of a .info with module names. All the output is simply the usage message for the command. Try running again with what the README states `zef install --deps-only .` whilst the terminal is at the root of this repository.

**Comment by anopperl** [comment]
still not working " zef install --deps-only . "

**Comment by bduggan** [comment]
Now that this project is in the ecosystem, you can just type `zef install Jupyter::Kernel`.  (The docs need to be updated).  After the install succeeds, just make sure that `jupyter-kernel.p6` is in your `PATH`.

**Comment by anopperl** [comment]
thanks bduggan its installed  .... but 
i dont have both path 
"cp etc/kernel.json ~/.local/share/jupyter/kernels/perl6 "

**Comment by bduggan** [comment]
Hi @anopperl,

I've made a few changes for portability, and I've updated the [configuration](https://github.com/bduggan/p6-jupyter-kernel#configuration) section of the README with new documentation.  As of the current version, you should be able to run

```
jupyter-kernel.p6 --generate-config
```

to generate a configuration file and place it in the default location (which [varies](http://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs)  depending on whether you are on OS/X, linux or Windows).  Alternatively, the sample configuration file is [here](https://github.com/bduggan/p6-jupyter-kernel/blob/master/resources/kernel.json) if you want to just copy it into place.

Brian
