### ISSUE TITLE
In jupyter-console only, most input commands seem to be evaluated twice.

### ISSUE THREAD

**Issue by ramillies** [bduggan/p6-jupyter-kernel#51]
I have installed the module in the usual way outlined in README and everything works well, except for the fact that in `jupyter-console`, most inputs seem to be evaluated twice. Nothing in client nor server configuration was changed, except for the kernel timeout and highlighting style, as per the README document. 

Here are some examples of the double evaluation:

    $  ~/.local/bin/jupyter-console --kernel=perl6
    Jupyter console 5.2.0  
    Welcome to Perl 6 (rakudo 2019.07.1).
    
    In [1]: say "Hello"
    Hello
    
    In [2]: my $a = 1
    Out[2]: 1
    
    In [3]: $a += 1
    Out[3]: 3 # It added 2×1 = 2 instead of 1.
    
    In [4]: $a *= 2
    Out[4]: 12 # It multiplied by 2×2 = 4 instead of 2.
    
    In [5]: my @b = 1,2,3
    Out[5]: [1 2 3]
    
    In [6]: @b.push(5)
    Out[6]: [1 2 3 5 5] # The 5 was pushed twice.
    
    In [7]: @b.splice(1,1)
    Out[7]: [3] # the first call removes and returns "2", the second does the same for "3".
                # Only the second return value is written into Out.
    
    In [8]: @b
    Out[8]: [1 5 5] # Both 2 and 3 were removed.

So any use of operator or method (or even a subroutine) was performed twice. The only exceptions I was able to found are the functions `say` and `print` which evaluate only once.

Oddly enough, this does *not* happen in the notebook. Everything is correctly evaluated only once there. I also experimented with the same console running Python and the double evaluation wasn't there, so I think this must be a bug connected to the Perl 6 kernel.

As for some system info: I use Debian bullseye/sid, Perl6 version is 2019.07.1, Jupyter version 5.2.0, and the Jupyter::Kernel module was installed using zef in the version 0.0.9. If you need any additional info, just ask and I will provide it.

Thanks!

**Comment by bduggan** [comment]
Thanks for the thorough report!  Yes, this definitely looks like an issue that needs to be fixed.  It seems that code that is being evaluated for the `is_complete_request` request is being persisted and re-executed again by the `execute_request`.  (The first type of request isn't necessary in the web UI since the entire cell is sent at once and executed, but the REPL needs to know whether to prompt for another line of input)

**Comment by bduggan** [comment]
This is fixed now -- a cell is executed when return is pressed, unless the contents [end with a backslash](https://github.com/bduggan/p6-jupyter-kernel/#usage-notes).
