### ISSUE TITLE
Install manually

### ISSUE THREAD

**Issue by qins** [bduggan/p6-jupyter-kernel#52]
Thanks for your excellent work!

However, what if someone cannot install this kernel by zef?

Is there a way to manually install?

**Comment by bduggan** [comment]
Hi @qins,

It is possible to install it manually -- just set the `PERL6LIB` environment variable to the directory containing the `lib` subdirectory.  You'll also want to install each of the dependencies manually, and add their `lib` directories to this search path.  You can find the dependencies in the file named `META6.json`

hope this helps
Brian
