### ISSUE TITLE
Get persistant history

### ISSUE THREAD

**Issue by tinmarino** [bduggan/p6-jupyter-kernel#55]
History off pasted command could persist and be retrived by `up` arrow:

I think it is just a few line and I'm on it.

https://github.com/bduggan/p6-jupyter-kernel/blob/26885c6e2f05005ca534a93a200580770808aad2/lib/Jupyter/Kernel.pm6#L161-L166

`jupyter_console` client implement it asking to `jupyter_client` to deliver the zmq command.

https://github.com/jupyter/jupyter_client/blob/fa0c78b97bc7183e1a6c0fa2f88fee943e52580e/jupyter_client/client.py#L331-L370

By the way, good job and pretty code. It is very useful for me, thanks

**Comment by bduggan** [comment]
Thanks and good point -- I agree -- it would be nice to have this!

**Comment by tinmarino** [comment]
Fixed by e48baf842ad5b4b9f58.
Thank you bduggan. I am happy now :-)
