### ISSUE TITLE
Feature: Operator definition are not persistent (just work in one line)

### ISSUE THREAD

**Issue by tinmarino** [bduggan/p6-jupyter-kernel#67]
Find a way to store them in `Handler.pm6`

**Comment by bduggan** [comment]
Yes, this is documented in the README (https://github.com/bduggan/p6-jupyter-kernel#known-issues) (see https://github.com/Raku/old-issue-tracker/issues/6333)

**Comment by tinmarino** [comment]
I understand, this is in the scope of Perl REPL
