### ISSUE TITLE
Kernels path?

### ISSUE THREAD

**Issue by MattOates** [bduggan/p6-jupyter-kernel#7]
Not convinced the README is right on where to put the kernel config. At least on Mac with Jupyter 5.0.0 the only thing that worked was `mkdir ~/.ipython/kernels/perl6 && cp etc/kernel.json ~/.ipython/kernels/perl6/`. Notice specifically the ending slash too the perl6 had to be a directory containing the kernel.json which even with the other .local path is not what the README states.

**Comment by bduggan** [comment]
Thanks for the details.  The parenthetical comment "`(or see 'jupyter --paths')`" was meant to address this, but it's probably a bit too terse.  You should be able to put the kernel into one of the directories listed in the `config` portion of the output of `jupyter --paths`.

**Comment by MattOates** [comment]
Looked into it more, the spec docs give some good per-platform defaults http://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs Which is a little confusing since its under the "data" section of the paths listed for me, so I wouldn't have put it there first.

How do you feel about automatically adding this stuff on installing the module to perhaps at least the user location unless running as root the the system? If you drop in http://mattoates.co.uk/files/perl6/logo-64x64.png and http://mattoates.co.uk/files/perl6/logo-32x32.png you also end up with a nice language specific icon within the web notebook.

**Comment by bduggan** [comment]
Great ideas!  I'll go ahead and reopen this issue until those are in place.

**Comment by bduggan** [comment]
All set; I ended up adding a `--generate-config` option instead of trying to do it completely automagically.
