### ISSUE TITLE
display() and MIME specific support?

### ISSUE THREAD

**Issue by MattOates** [bduggan/p6-jupyter-kernel#8]
Given this is my third "issue" in as many hours. I should probably say, this is an awesome development and Im just really excited.

My [second nonsense test in the Notebook](http://mattoates.co.uk/files/perl6/jupyter_perl6_plot_test.png) was perhaps a bit mean and also a bit ambitious 😸  But it would be quite cool to be able to get an all Perl SVG plot going.

So at the moment text/plain is the assumed mime type for all of the messages sent from the kernel I think? Do you have any plans to add in the display() like functionality sending the right mime headers? I'm more than happy to try and help out on this. The [Julia implementation](https://github.com/JuliaLang/IJulia.jl/blob/master/src/inline.jl) might have some hints, they at least list the more major mime types recognised. It might be possible to do something nice with mixed in roles and meta programming in Perl 6 to get this functionality without needing the explicit display()

**Comment by MattOates** [comment]
Ok so just replace to text/html [is magical](http://mattoates.co.uk/files/perl6/jupyter_perl6_plot_test_html.png)!!!

**Comment by bduggan** [comment]
Thanks, and yes, better MIME-type support would be great!

**Comment by bduggan** [comment]
I've added some minimal support -- just SVGs in results or in stdout -- feel free to extend this if you have a chance!
