### ISSUE TITLE
Syntax highlighting in notebook

### ISSUE THREAD

**Issue by samebchase** [bduggan/p6-jupyter-kernel#92]
I was able to get syntax highlighting in the console, but how do we enable it for the notebook?

**Comment by bduggan** [comment]
This is done by CodeMirror -- neither Raku nor Perl 6 are in their [list of languages](https://codemirror.net/mode/index.html), but it looks like some outside work has been done to support [perl6](https://www.google.com/search?q=codemirror+perl6)

**Comment by samebchase** [comment]
Ah, thanks.
