### ISSUE TITLE
perl6 on Binder unresponsive

### ISSUE THREAD

**Issue by p6steve** [bduggan/p6-jupyter-kernel#94]
Hi - I am trying to consume this codebase - works fine on my local machine, but Binder (after the usual 10-15 mins build time) shows my notebook files fine, can connect to the Raku kernel, but the first cell with code just freezes with [*]

Was working fine for months beforehand by the way.

I have tried commenting out all but the first couple of my zef installs beyond your standard Dockerfile and this behaviour happens even with just these two.

RUN apt-get update \
    && apt-get install -y build-essential \
    wget libzmq3-dev ca-certificates \
    python3-pip python3-setuptools \
    && rm -rf /var/lib/apt/lists/* && pip3 install jupyter notebook asciinema jupyterlab pyscaffold --no-cache-dir \
    && zef -v install git://github.com/bduggan/p6-jupyter-kernel.git --force-test \
    && zef install SVG::Plot --force-test \
    && zef -v install Math::Polygons --force-test \
    && zef -v install https://github.com/p6steve/raku-Physics-Unit.git@v1.1.3 --force-test \
    #&& zef -v install https://github.com/p6steve/raku-Physics-Measure.git@v1.0.0 --force-test \
    #&& git clone https://github.com/p6steve/raku-Physics-Measure-JupyterBinder.git \
    #&& mv raku-Physics-Measure-JupyterBinder/eg ${HOME} \
    #&& rm -rf raku-Physics-Measure-JupyterBinder \
    && jupyter-kernel.raku --generate-config \
    && ln -s /usr/share/perl6/site/bin/* /usr/local/bin

**Comment by bduggan** [comment]
So, some findings from a little investigation, just using the binder link from the readme.

1. If you change the last part of the url to "lab", you'll have the jupyter lab interface -- from there it's possible to open a terminal in the browser.  After this, running `jupyter-console --kernel=raku` seems to work fine -- so I think Docker and the kernel are working fine -- the issue is somewhere in the web interface.
2. Looking at the browser console in firefox, I see `Firefox can’t establish a connection to the server at wss://....` -- there is something going wrong establishing a websocket connection.
3. When I switch browsers -- and try chrome instead -- it doesn't work initially, but after restarting the kernel it then works fine.
4. The python kernel seems to work fine on both browsers.

I think some more work is still necessary to figure out the source of the problem -- but at least there seems to be a workaround (use chrome, and restart the kernel?)  Any more information about the specific environments in which this occurs would be helpful.

**Comment by p6steve** [comment]
Thanks for coming back (sorry for my slow response), I have tried two steps to operate the work around.

Short update is: my Dockerfile now is reverted a clone of yours (no additional Physics::Measure items period); the workaround doesn't work for me. I see similar web socket errors.

Maybe we could raise an issue on Binder?
 
(1) this url (on Chrome)
https://mybinder.org/v2/gh/p6steve/raku-Physics-Measure-Jupyter/master?urlpath=lab
- first pass it reloaded my already built/failed image in 'lab'
- console would not connect despite restart kernel 'raku console status | unknown' bottom left status footer
(2)
reverting my Docker to be a clone of yours (to get back to working)
- noticed one build error in the Binder build log
Successfully built asciinema pandocfilters pyrsistent
ERROR: requests 2.25.1 has requirement idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.
- python console running fine
- raku console 'status|unknown'
- restart raku kernel in this console
- raku - restarting .... nothing doing after 6 mins
- Chrome Developer JS console dump vvvvvvvv

Uncaught (in promise) Error: Canceled future for kernel_info_request message before replies were done
    at u.dispose (jlab_core.61e1fcd0f32a80614a78.js:2)
    at jlab_core.61e1fcd0f32a80614a78.js:2
    at Map.forEach (<anonymous>)
    at C._clearKernelState (jlab_core.61e1fcd0f32a80614a78.js:2)
    at C.restart (jlab_core.61e1fcd0f32a80614a78.js:2)
    at J.restartKernel (jlab_core.61e1fcd0f32a80614a78.js:2)
    at Object.restart (jlab_core.61e1fcd0f32a80614a78.js:2)
jlab_core.61e1fcd0f32a80614a78.js:2 Uncaught (in promise) Error: Canceled future for history_request message before replies were done
    at u.dispose (jlab_core.61e1fcd0f32a80614a78.js:2)
    at jlab_core.61e1fcd0f32a80614a78.js:2
    at Map.forEach (<anonymous>)
    at C._clearKernelState (jlab_core.61e1fcd0f32a80614a78.js:2)
    at C.restart (jlab_core.61e1fcd0f32a80614a78.js:2)
    at J.restartKernel (jlab_core.61e1fcd0f32a80614a78.js:2)
    at Object.restart (jlab_core.61e1fcd0f32a80614a78.js:2)
jlab_core.61e1fcd0f32a80614a78.js:2 Uncaught (in promise) Error: Canceled future for kernel_info_request message before replies were done
    at u.dispose (jlab_core.61e1fcd0f32a80614a78.js:2)
    at jlab_core.61e1fcd0f32a80614a78.js:2
    at Map.forEach (<anonymous>)
    at C._clearKernelState (jlab_core.61e1fcd0f32a80614a78.js:2)
    at C.restart (jlab_core.61e1fcd0f32a80614a78.js:2)
    at J.restartKernel (jlab_core.61e1fcd0f32a80614a78.js:2)
    at Object.restart (jlab_core.61e1fcd0f32a80614a78.js:2)
jlab_core.61e1fcd0f32a80614a78.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.61e1fcd0f32a80614a78.js:2
jlab_core.61e1fcd0f32a80614a78.js:2 WebSocket connection to 'wss://hub.gke2.mybinder.org/user/p6steve-raku-ph-measure-jupyter-33o79b73/api/kernels/b61197d6-35aa-430f-b9db-e9694913ac71/channels?session_id=daadc69c-2805-4e54-91ee-f0de9bb356f5' failed: WebSocket is closed before the connection is established.
_clearSocket @ jlab_core.61e1fcd0f32a80614a78.js:2
jlab_core.61e1fcd0f32a80614a78.js:2 WebSocket connection to 'wss://hub.gke2.mybinder.org/user/p6steve-raku-ph-measure-jupyter-33o79b73/api/kernels/b61197d6-35aa-430f-b9db-e9694913ac71/channels?session_id=e974ec95-8d0c-421b-aadd-8530a7ccc3fd' failed: Error during WebSocket handshake: Unexpected response code: 504
C._createSocket @ jlab_core.61e1fcd0f32a80614a78.js:2
jlab_core.61e1fcd0f32a80614a78.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.61e1fcd0f32a80614a78.js:2
jlab_core.61e1fcd0f32a80614a78.js:2 WebSocket connection to 'wss://hub.gke2.mybinder.org/user/p6steve-raku-ph-measure-jupyter-33o79b73/api/kernels/b61197d6-35aa-430f-b9db-e9694913ac71/channels?session_id=f591f2b4-3506-455a-877a-ff96a72f5ec3' failed: WebSocket opening handshake timed out
C._createSocket @ jlab_core.61e1fcd0f32a80614a78.js:2
jlab_core.61e1fcd0f32a80614a78.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.61e1fcd0f32a80614a78.js:2
C._onWSClose @ jlab_core.61e1fcd0f32a80614a78.js:2
jlab_core.61e1fcd0f32a80614a78.js:2 WebSocket connection to 'wss://hub.gke2.mybinder.org/user/p6steve-raku-ph-measure-jupyter-33o79b73/api/kernels/b61197d6-35aa-430f-b9db-e9694913ac71/channels?session_id=daadc69c-2805-4e54-91ee-f0de9bb356f5' failed: WebSocket opening handshake timed out
C._createSocket @ jlab_core.61e1fcd0f32a80614a78.js:2
jlab_core.61e1fcd0f32a80614a78.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.61e1fcd0f32a80614a78.js:2
C._onWSClose @ jlab_core.61e1fcd0f32a80614a78.js:2

**Comment by bduggan** [comment]
On your URL I was able to click 'terminal' and get a terminal -- tailing `jupyter.log` shows this:

```
2021-02-10T13:41:52.155024Z (10) debug: shell got a message: comm_info_request
2021-02-10T13:41:52.155738Z (10) warning: unimplemented message type: comm_info_request
```

This may be a clue

**Comment by bduggan** [comment]
Another workaround -- this seems to work across browsers: after running the first cell, click the stop (⏹) button, observe that the cell now contains something like `[got sigint on thread 10]`.  Then try again -- everything seems to work fine.

So, now I am suspecting that perhaps precompilation is slowing down the first response, but after that everything works fine.

**Comment by p6steve** [comment]
Thanks for the explanation... 
but, my conception is that precomp is done by zef --force-test, isn't it?

**Comment by bduggan** [comment]
Yeah...i would think so too, or also when generating the configuration

**Comment by p6steve** [comment]
The workaround seems to do the trick, but quite irksome for a newcomer to a topic to jump through that hoop... really appreciate your support.

**Comment by bduggan** [comment]
Agreed -- would be nice to get to the bottom of this!

**Comment by bduggan** [comment]
Looks like this is the reason:

https://github.com/jupyter/notebook/commit/7a3ae6e4a4bfbef9e722f2bad4c9532f96010cf4

> # Nudge the kernel with kernel info requests until we get an IOPub message

Because of this change, the client continues to send kernel info requests until it gets a response on the iopub channel.

I'll make a change to send a message on that channel

**Comment by bduggan** [comment]
I suppose eventually this new behavior will be documented here

https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-info

It's not entirely clear what should happen if the server is busy working when an info request is received

**Comment by p6steve** [comment]
that solves it! many thanks...
