### ISSUE TITLE
Can't zef install on linux/arm64

### ISSUE THREAD

**Issue by p6steve** [bduggan/p6-jupyter-kernel#96]
Hi

Thanks for this excellent module. I notice that the Dockerfile has inverted from FROM all-spark-notebook to FROM rakudo ... I am trying to maintain the previous approach because (i) I need --platform=linux/arm64 and rakudo build doesn't yet have this and (ii) I also need good python, vi, bash history etc and that's all in all-spark-notebook

BUT when I do this Dockerfile it works fine (ie. launches vanilla jupyter-notebook) until I get to the line:
zef -v install https://github.com/bduggan/p6-jupyter-kernel.git@master 

The errors are below the Dockerfile. Any thoughts?

Welcome to Rakudo(tm) v2021.04.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.

```
FROM --platform=linux/arm64 jupyter/all-spark-notebook:latest

USER root

ENV NB_USER jovyan
ENV NB_UID 100
ENV HOME /home/${NB_USER}

ENV PATH /usr/share/perl6/site/bin:$PATH

RUN apt-get update \
  && apt-get install -y build-essential \
  && git clone https://github.com/rakudo/rakudo.git -b 2021.04 \
  && cd rakudo && perl Configure.pl --prefix=/usr --gen-moar --gen-nqp --backends=moar \
  && make && make install && cd .. && rm -rf rakudo \
  && export PATH=$PATH:/usr/share/perl6/site/bin \
  && git clone https://github.com/ugexe/zef.git \
     && cd zef && raku -Ilib bin/zef install . \
     && cd .. && rm -rf zef \
#  && zef -v install https://github.com/bduggan/p6-jupyter-kernel.git@master \
#  && zef -v install SVG::Plot --force-test \
#  && zef -v install https://github.com/p6steve/perl6-Math-Polygons.git \
#  && git clone https://github.com/p6steve/perl6-Math-Polygons.git \
#  && mv perl6-Math-Polygons/eg ${HOME} \
#  && rm -rf perl6-Math-Polygons \
  && chown -R $NB_UID ${HOME} \
  && fix-permissions ${HOME} \
#  && jupyter-kernel.p6 --generate-config
  && jupyter notebook --generate-config -y

USER ${NB_USER}

ENTRYPOINT ["/bin/bash"]
```

===> Building: Digest::SHA256::Native:ver<0.03>
[Digest::SHA256::Native] Command: /usr/bin/rakudo-m -I/home/jovyan/.zef/tmp/P6-LibraryMake.git/1c6bf1d0e427e51d880ac237e6d168c4919adbfd -I/home/jovyan/.zef/tmp/Shell-Command.git/1145ea0ff71507b2fe932fca6d2a68d4004c7d12 -I/home/jovyan/.zef/tmp/perl6-file-which.git/1dfbeba2f92f8b2b04e8b26619eb20d599198d25 -I/home/jovyan/.zef/tmp/File-Find.git/89ad430ab08c78aa3c9181bb0b3020f1e2d01b32 -e require '/home/jovyan/.zef/tmp/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03/Build.pm'; ::('Build').new.build('/home/jovyan/.zef/tmp/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03') ?? exit(0) !! exit(1);
[Digest::SHA256::Native] /opt/conda/bin/aarch64-conda-linux-gnu-cc -c -fPIC -std=gnu99 -Wextra -Wall -Wno-unused-parameter -Wno-unused-function -Wno-missing-braces -Werror=pointer-arith -O3 -DNDEBUG  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DMVM_HEAPSNAPSHOT_FORMAT=2 -o  sha256.o src/sha256.c
[Digest::SHA256::Native] /opt/conda/bin/aarch64-conda-linux-gnu-ld -shared -fPIC -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib  -lm -lpthread -lrt -ldl -o /home/jovyan/.zef/tmp/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03/resources/libraries/libsha256.so sha256.o
[Digest::SHA256::Native] /opt/conda/bin/aarch64-conda-linux-gnu-ld: unrecognized option '-Wl,-O2'
[Digest::SHA256::Native] /opt/conda/bin/aarch64-conda-linux-gnu-ld: use the --help option for usage information
[Digest::SHA256::Native] make: *** [Makefile:9: /home/jovyan/.zef/tmp/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03/resources/libraries/libsha256.so] Error 1
[Digest::SHA256::Native] The spawned command 'make' exited unsuccessfully (exit code: 2, signal: 0)
[Digest::SHA256::Native]   in method build at /home/jovyan/.zef/tmp/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03/Build.pm line 14
[Digest::SHA256::Native]   in block <unit> at -e line 1
===> Building [FAIL]: Digest::SHA256::Native:ver<0.03>
Aborting due to build failure: Digest::SHA256::Native:ver<0.03> (use --force-build to override)

**Comment by bduggan** [comment]
Hmm -- so...let's see...looks like `Digest::SHA256::Native` is failing to build:
```
/opt/conda/bin/aarch64-conda-linux-gnu-ld -shared -fPIC -Wl,-O2 -Wl,--sort-common -Wl,--as-needed
-Wl,-z,relro -Wl,-z,now -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib  -lm -lpthread -lrt -ldl
-o /home/jovyan/.zef/tmp/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03/resources/libraries/libsha256.so
sha256.o
[Digest::SHA256::Native] /opt/conda/bin/aarch64-conda-linux-gnu-ld: unrecognized option '-Wl,-O2'
```
these flags come from LibraryMake -- https://github.com/retupmoca/P6-LibraryMake/blob/master/lib/LibraryMake.pm6#L146 -- which come from $*VM.config -- https://docs.raku.org/language/variables#index-entry-$*VM -- so I guess these are set when moarvm is built.

Perhaps the compiler being used here is different than the one used for moarvm -- i.e. maybe `/opt/conda/bin` is earlier in the path than the path to another instance of `gcc`?  I would probably stop the docker build at that point and see what the right settings are to ensure that the same compiler is used.  (maybe just prepending something else to `PATH` will do the trick?)

**Comment by p6steve** [comment]
Thanks @bduggan ! - that's great advice the perfect level of info for a hacker like me to have a crack at a solution - I will report back...

**Comment by p6steve** [comment]
What works for me (ie. to get raku jupyter notebook up on arm64) is this:

1. Adjust https://github.com/sumanstats/rakudo ...
[https://github.com/sumanstats/rakudo/blob/main/2021.05/Dockerfile]

So that these items (ie. Digest::SHA256::Native deps) are installed with the raku toolchain
	&& zef install JSON::Tiny Digest::HMAC Digest::SHA256::Native \

Before we purge ahead of the anaconda toolchain
     && apt-get purge -y --auto-remove $buildDeps

2. No change then needed to Dockerfiles
https://github.com/sumanstats/raku-notebook
-and-
https://github.com/bduggan/p6-jupyter-kernel
 
(except to wire up FROM **item #1**)

**Comment by bduggan** [comment]
Interesting -- thanks for digging into this.
